# Generated by Django 3.2.19 on 2023-07-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.CharField(max_length=255, verbose_name='域名')),
                ('ping_ret', models.CharField(max_length=255, verbose_name='ping返回值')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'tb_domain',
                'verbose_name_plural': 'tb_domain',
            },
        ),
    ]
